"""init migration

Revision ID: 36853035f3cd
Revises: 47a55c998e59
Create Date: 2025-07-25 14:31:21.268318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36853035f3cd'
down_revision: Union[str, Sequence[str], None] = '47a55c998e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('auto_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'auto_id')
    # ### end Alembic commands ###
