"""init migration

Revision ID: 47a55c998e59
Revises: 4863ef703f39
Create Date: 2025-07-25 14:15:57.250194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a55c998e59'
down_revision: Union[str, Sequence[str], None] = '4863ef703f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('auto', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('auto', sa.Column('model', sa.String(), nullable=True))
    op.add_column('auto', sa.Column('year_of_release', sa.Integer(), nullable=True))
    op.add_column('auto', sa.Column('mileage', sa.Integer(), nullable=True))
    op.add_column('auto', sa.Column('location', sa.String(), nullable=True))
    op.add_column('auto', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('auto', sa.Column('min_installment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'min_installment')
    op.drop_column('auto', 'price')
    op.drop_column('auto', 'location')
    op.drop_column('auto', 'mileage')
    op.drop_column('auto', 'year_of_release')
    op.drop_column('auto', 'model')
    op.drop_column('auto', 'brand')
    op.drop_column('auto', 'image_url')
    # ### end Alembic commands ###
