"""add vin to auto table

Revision ID: 82ff2dbd8162
Revises: 30ea175080ea
Create Date: 2025-07-30 15:51:07.868931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ff2dbd8162'
down_revision: Union[str, Sequence[str], None] = '30ea175080ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('vin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'vin')
    # ### end Alembic commands ###
