"""init migration

Revision ID: f4d40334ddcb
Revises: 36853035f3cd
Create Date: 2025-07-25 14:31:43.586224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d40334ddcb'
down_revision: Union[str, Sequence[str], None] = '36853035f3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auto_auto_id'), 'auto', ['auto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_auto_id'), table_name='auto')
    # ### end Alembic commands ###
